name: CI/CD Pipeline

trigger:
- main
pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'Microsoft.IO.RecyclableMemoryStream.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
      - job: data_gathering
        displayName: Data gathering
        steps:
          - pwsh: |
              git checkout feature/docs-2
              get-childitem
            displayName: Test script

          # - task: UseDotNet@2
          #   displayName: 'Use .NET Core SDK'
          #   inputs:
          #     packageType: sdk
          #     version: 5.0.203
          #     installationPath: $(Agent.ToolsDirectory)/dotnet