name: CI/CD Pipeline

trigger:
- main
pr:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Microsoft.IO.RecyclableMemoryStream'
  date: $(Date:yyyyMMdd)
  solution: 'Microsoft.IO.RecyclableMemoryStream.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
      - job: build_validation
        displayName: Build validation
        steps:
          - pwsh: |
              git checkout feature/docs-2
              get-childitem
            displayName: Test script

          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK'
            inputs:
              packageType: sdk
              version: 5.0.203
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '$(solution)'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release --no-restore'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '$(solution)'
              arguments: '--configuration Release --logger "trx;LogFileName=$(projectName)-$(date).trx;verbosity=normal" --results-directory "Test results/" --no-build'
              publishTestResults: false