name: CI/CD Pipeline

trigger:
- master
pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: 'Microsoft.IO.RecyclableMemoryStream'
  solution: 'Microsoft.IO.RecyclableMemoryStream.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# Stage CI
## Jobs
### Job: build, test and artifact generation
#### pwsh: Data gatherer
#### pwsh: Conditionals handler
#### pwsh: Tag generator
#### pwsh: Project version determiner
#### task: restore
#### task: build Debug
#### task: copy bin to b/ and a/
#### task: upload assemblies
#### task: test
#### task: upload test results
#### task: pack Release
#### task: upload package

# Stage CD
## Jobs
### Job: Package Deployment
### Job: GitHub Release

stages:
  - stage: ci
    displayName: Continuous Integration
    jobs:
      - job: build_validation
        displayName: Build validation
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK'
            inputs:
              packageType: sdk
              version: 5.0.203
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: '$(solution)'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release --no-restore'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'test'
              projects: '$(solution)'
              arguments: '--configuration Release --logger trx;LogFileName=$(projectName)-$(Date:yyyyMMdd).trx;verbosity=normal --results-directory "Test results/" --no-build'
              publishTestResults: false

          - pwsh: |
              get-childitem
            displayName: Check files

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: 'Test results/'
              artifact: 'Test results'
              publishLocation: 'pipeline'